name: instagram_basic_display_api_flutter
description: A sample implementing the IG basic display API.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_auth: ^2.0.5
  simple_auth_flutter: ^2.0.4
  dio: ^3.0.9

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
